### ISSUE TITLE
Ability to go unlimited years back?

### ISSUE THREAD

**Issue by joshuarudd** [Kageetai/obsidian-plugin-journal-review#2]
First off, excellent plugin! I've been looking for something like this for awhile now for my journal entries (I used to use DayOne for journaling, and loved the ability to see an "On this day" list of entries). Just when I figured I should probably create a plugin myself, lo and behold: I learned about this one on Eleanor Kong's weekly newsletter.

Now to my feature request: because I have decades of journal entries, I'd love to not have to enter in a new line for each year back that I want to include. For example, my "Time Spans" setting is currently includes a separate line for the past 33 years. I don't want to have to keep adding more years as the years go on.

Thanks again for creating this!

**Comment by Kageetai** [comment]
Hello and first and foremost, thanks a lot for the kind words. This is my first try writing a plugin for Obsidian, also mostly for my own use case, because I also liked the same feature in other diary apps :)
I wasn't even notified my plugin was mentioned in that newsletter. Thanks for letting me know.

For your feature request, I also had the same idea, but wanted to keep it the most flexible in the beginning. How would you imagine that setting to look then? I could imagine a dropdown and number input for each type of time span, like "years", "months", 'week" and "days". What do you think?

**Comment by Kageetai** [comment]
Hey there,
I know it's been a while, but I finally had time to manage to release a new version [2.0.0](https://github.com/Kageetai/obsidian-plugin-journal-review/releases/tag/2.0.0).
This should allow unlimited time spans and generally more flexibility.
Can you please test this and let me know if this works with your "decades of journal entries", as I don't have such an extensive archive yet :)
Thx and I will in the meantime close this issue. Feel free to reopen if something doesn't work.

**Comment by joshuarudd** [comment]
@Kageetai hey! Just updated the plugin. The "Recurring?" functionality makes all the difference! From a usability standpoint, the sliders are a bit awkward for adjusting numbers since I'm trying to enter an exact value, but that's just a minor nuisance.

Thanks again for this update!

**Comment by Kageetai** [comment]
Yeah, I also am not a fan of these sliders, for simplicity and consistency with the general interface, I thought to just reuse the options for settings that Obsidian provides. Using a plain input field, I would need to make sure the input is always converted etc. and these sliders already make sure of that.

But glad the recurring feature works well for you. :)
