### ISSUE TITLE
Preview doesn't load

### ISSUE THREAD

**Issue by alexander-potemkin** [Kageetai/obsidian-plugin-journal-review#5]
Quite often but with no clear pattern, preview for non 1st and non last time spans doesn't load...
I've changed the default lines parameter, but I don't expect that to impact, or am I missing something?

**Comment by Kageetai** [comment]
Similar to my comment on [the other issue](https://github.com/Kageetai/obsidian-plugin-journal-review/issues/4#issuecomment-1593297273) from you, this could have to do with the view not updating correctly on changed settings etc.
When it happens, can you tell me which date you are on and which dates you expect to be rendered?

**Comment by alexander-potemkin** [comment]
Yeah, but I didn't change the preview settings... It's not happening all of the times - let me revert back to you once I have it reproduced. Is there some debug logs or additional information (except for the dates) that I could provide?

**Comment by alexander-potemkin** [comment]
<img width="333" alt="Obsidian Plugin issue" src="https://github.com/Kageetai/obsidian-plugin-journal-review/assets/2323840/250e897a-db69-4816-998f-82497b6ac6c5">

Found another way to reproduce that: when I split the right panel with journal on it, it won't show the content at the bottom side of the journal, regardless of the space I give it (screenshot attached).

**Comment by Kageetai** [comment]
Hey, thanks for investigating further and checking. I promise I did not abandon this little project, was just way too busy recently, but had this on my mind.
Your comment actually gave me an idea and a little push to check something. I never opened the view like this, with the same view open more than once, but this made me realize I made a mistake when rendering the previews.
I fixed this now in the latest [1.0.3 release](https://github.com/Kageetai/obsidian-plugin-journal-review/releases/tag/1.0.3) (with some other minor style changes), so could you give this a try and check whether your original issue might also be fixed with that?

**Comment by alexander-potemkin** [comment]
I didn't think you are and I really appreciate the things you do!

Thank you -  I've updated, tried to split the screen and the view is quite the same - no text below the headers on the bottom pane... 🙁

**Comment by Kageetai** [comment]
Ah, right. Totally forgot to update the version in all corresponding files, should be correct now 😅

**Comment by alexander-potemkin** [comment]
It does! Thanks a lot!! 🙂
